import { ContentWrapper } from "@/components/content-wrapper";
import "./globals.css";
import Head from "next/head";
import Providers from "./providers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <>
      <Head>
        <title>{metadata?.title}</title>
        <meta name="description" content={metadata.description} />
      </Head>
      <ContentWrapper>{children}</ContentWrapper>
    </>
  );
};

export default RootLayout;
